---
title: "cost_falsedec_as_x"
author: "JM and HN"
date: "2023-07-12"
output: html_document
---

# build table, cost of hi, cr = 1 and fa, mi = cost_hi * x, IDK = 0: ----
```{r table-all-x-IDK-0}
# Define x: ----
x <- seq(-10, 0, length.out = 100)

# Variables needed:----
cost_IDK <- 0
cost_hi <- -1
cost_IDK_hi <- cost_IDK
cost_IDK_mi <- cost_IDK
cost_mi <- x * cost_hi
cost_fa <- cost_mi
cost_IDK_fa <- cost_IDK
cost_IDK_cr <- cost_IDK
cost_cr <- cost_hi

# Calculate all y: ----
# Calculate y1 for each x value:
original <- pc_original_table$`TRUE (reality) %`[1] * cost_hi +
      pc_original_table$`TRUE (reality) %`[2] * cost_mi +
      pc_original_table$`FALSE (reality) %`[1] * cost_fa +
      pc_original_table$`FALSE (reality) %`[2] * cost_cr

# Calculate y2 for each x value (example calculation):
IDK_1 <- pc_table$`TRUE (reality) %`[1] * cost_hi +
               pc_table$`TRUE (reality) %`[2] * cost_IDK_hi +
               pc_table$`TRUE (reality) %`[3] * cost_IDK_mi +
               pc_table$`TRUE (reality) %`[4] * cost_mi +
               pc_table$`FALSE (reality) %`[1] * cost_fa +
               pc_table$`FALSE (reality) %`[2] * cost_IDK_fa +
               pc_table$`FALSE (reality) %`[3] * cost_IDK_cr +
               pc_table$`FALSE (reality) %`[4] * cost_cr 

# Calculate y3 for each x value (example calculation):
IDK_all <- pc_table_all$`TRUE (reality) %`[1] * cost_hi +
  pc_table_all$`TRUE (reality) %`[2] * cost_IDK_hi +
  pc_table_all$`TRUE (reality) %`[3] * cost_IDK_mi +
  pc_table_all$`TRUE (reality) %`[4] * cost_mi +
  pc_table_all$`FALSE (reality) %`[1] * cost_fa +
  pc_table_all$`FALSE (reality) %`[2] * cost_IDK_fa +
  pc_table_all$`FALSE (reality) %`[3] * cost_IDK_cr +
  pc_table_all$`FALSE (reality) %`[4] * cost_cr 

# Calculate y4:
 FFT_handle <- key_results$mn_hi[2] * cost_hi +
                    key_results$mn_mi[2] * cost_mi +
                    key_results$mn_fa[2] * cost_fa +
                    key_results$mn_cr[2] * cost_cr 

# Plot the graph with multiple y variables: ----
plot(x, original, type = "l",ylim = c(-2,2), col = "red", xlab = "costs false decisions (x * correct decisions)", ylab = "Costs",
main = "Total costs depending on the relationship from costs of false to correct decisions.")
lines(x, IDK_1, col = "darkgreen")
lines(x, IDK_all, col = "green")
lines(x, FFT_handle, col = "orange")

# Add a legend to the graph
legend("bottomleft", legend = c("Original Data", "IDK_one_node", "IDK_all_nodes", "FFT_handle_NAs"), col = c("red", "darkgreen", "green", "orange"), lty = 1)

```


# calculations ----

```{r Intersection-original-1-IDk}
# Define the two functions: ----
original <-  function(x) pc_original_table$`TRUE (reality) %`[1] * cost_hi +
      pc_original_table$`TRUE (reality) %`[2] *  x * cost_hi +
      pc_original_table$`FALSE (reality) %`[1] *  x * cost_hi +
      pc_original_table$`FALSE (reality) %`[2] * cost_cr


one_IDK <- function(x)pc_table$`TRUE (reality) %`[1] * cost_hi +
               pc_table$`TRUE (reality) %`[2] * cost_IDK_hi +
               pc_table$`TRUE (reality) %`[3] * cost_IDK_mi +
               pc_table$`TRUE (reality) %`[4] *  x * cost_hi +
               pc_table$`FALSE (reality) %`[1] *  x * cost_hi +
               pc_table$`FALSE (reality) %`[2] * cost_IDK_fa +
               pc_table$`FALSE (reality) %`[3] * cost_IDK_cr +
               pc_table$`FALSE (reality) %`[4] * cost_cr 
    


# Find the intersection point: ----
intersection <- uniroot(function(x)  one_IDK(x) - original(x), interval = c(-1000, 1000))
intersection_point_IDK_1_original <- intersection$root

# Print the intersection point:
intersection_point_IDK_1_original
```

```{r Intersection-FFT-handle-1-IDk}
# Define the two functions: ----
FFT_handle <-  function(x) key_results$mn_hi[2] * cost_hi +
                    key_results$mn_mi[2] * x * cost_hi +
                    key_results$mn_fa[2] * x * cost_hi +
                    key_results$mn_cr[2] * cost_cr 


one_IDK <- function(x)pc_table$`TRUE (reality) %`[1] * cost_hi +
               pc_table$`TRUE (reality) %`[2] * cost_IDK_hi +
               pc_table$`TRUE (reality) %`[3] * cost_IDK_mi +
               pc_table$`TRUE (reality) %`[4] *  x * cost_hi +
               pc_table$`FALSE (reality) %`[1] *  x * cost_hi +
               pc_table$`FALSE (reality) %`[2] * cost_IDK_fa +
               pc_table$`FALSE (reality) %`[3] * cost_IDK_cr +
               pc_table$`FALSE (reality) %`[4] * cost_cr 
    

# Find the intersection point: ----
intersection <- uniroot(function(x)  one_IDK(x)  - FFT_handle(x), interval = c(-1000, 1000))
intersection_point_IDK_1_FFT_handle <- intersection$root

# Print the intersection point:
intersection_point_IDK_1_FFT_handle
```

```{r Intersection-original-all-IDk}
# Define the two functions: ----
original <-  function(x) pc_original_table$`TRUE (reality) %`[1] * cost_hi +
      pc_original_table$`TRUE (reality) %`[2] *  x * cost_hi +
      pc_original_table$`FALSE (reality) %`[1] *  x * cost_hi +
      pc_original_table$`FALSE (reality) %`[2] * cost_cr


all_IDK <- function(x) pc_table_all$`TRUE (reality) %`[1] * cost_hi +
  pc_table_all$`TRUE (reality) %`[2] * cost_IDK_hi +
  pc_table_all$`TRUE (reality) %`[3] * cost_IDK_mi +
  pc_table_all$`TRUE (reality) %`[4] * x * cost_hi +
  pc_table_all$`FALSE (reality) %`[1] * x * cost_hi +
  pc_table_all$`FALSE (reality) %`[2] * cost_IDK_fa +
  pc_table_all$`FALSE (reality) %`[3] * cost_IDK_cr +
  pc_table_all$`FALSE (reality) %`[4] * cost_cr 
  
  
# Find the intersection point: ----
intersection <- uniroot(function(x)  all_IDK(x) - original(x), interval = c(-1000, 1000))
intersection_point_IDK_all_original <- intersection$root

# Print the intersection point
intersection_point_IDK_all_original
```

```{r Intersection-FFT-handle-all-IDk}
# Define the two functions: ----
FFT_handle <-  function(x) key_results$mn_hi[2] * cost_hi +
                    key_results$mn_mi[2] * x * cost_hi +
                    key_results$mn_fa[2] * x * cost_hi +
                    key_results$mn_cr[2] * cost_cr 

all_IDK <- function(x) pc_table_all$`TRUE (reality) %`[1] * cost_hi +
  pc_table_all$`TRUE (reality) %`[2] * cost_IDK_hi +
  pc_table_all$`TRUE (reality) %`[3] * cost_IDK_mi +
  pc_table_all$`TRUE (reality) %`[4] * x * cost_hi +
  pc_table_all$`FALSE (reality) %`[1] * x * cost_hi +
  pc_table_all$`FALSE (reality) %`[2] * cost_IDK_fa +
  pc_table_all$`FALSE (reality) %`[3] * cost_IDK_cr +
  pc_table_all$`FALSE (reality) %`[4] * cost_cr 


# Find the intersection point: ----
intersection <- uniroot(function(x)  all_IDK(x) - FFT_handle(x), interval = c(-1000, 1000))
intersection_point_IDK_all_FFT_handle <- intersection$root

# Print the intersection point
intersection_point_IDK_all_FFT_handle
```

```{r collect-intersection-points}
# collect all intersection points: ----
all_intersection_points <- c(intersection_point_IDK_1_original, intersection_point_IDK_1_FFT_handle, intersection_point_IDK_all_original, intersection_point_IDK_all_FFT_handle )

# filter only important variable: 
costs_false_intersections_60 <- all_intersection_points
```

```{r display-intersection-points}
# display saved performance: ----
costs_false_intersections_05
costs_false_intersections_10
costs_false_intersections_20
costs_false_intersections_25 
costs_false_intersections_50
costs_false_intersections_75
costs_false_intersections_60
costs_false_intersections_100
```
