---
title: "plot_thresholds_diffr_pcs_missings"
author: "JM and HN"
date: "2023-07-12"
output: html_document
---
```{r compare-1-IDK-FFT-handle-false-decision-is-x}

# define the costs of false decision where 1_IDK and FFT_handle fucntion meet:
costs_false_decisions <- c(costs_false_intersections_05[2],
costs_false_intersections_10[2],
costs_false_intersections_20[2],
costs_false_intersections_25[2], 
costs_false_intersections_50[2],
costs_false_intersections_60[2],
costs_false_intersections_75[2],
costs_false_intersections_100[2])

# define pc that is missing: 
pc_missings <- c(5, 10, 20, 25, 50, 60, 75, 100)

# plot both and a vertical line at 0, that is the cost of IDK decisions: 
plot(pc_missings, costs_false_decisions , type='o',lty=2,col='darkgreen',lwd=1, main = "Costs of False decisions, where when more expensive 1_IDK starts performing better than FFT_handle.")
abline(h = 0, col='red',lty = 2)





```

```{r calculate-at-which-pc-missings-costs-of-false-decision-only-has-to-be-as-good-as-no-decision-for-fft-handle-to-have-lower-costs}

# Define the function for the line connecting the points:
line_function <- function(x) {
  approx(x = pc_missings, y = costs_false_decisions, xout = x)$y
}

# Find the intersection point with the vertical line:
intersection <- uniroot(function(x) line_function(x), interval = range(pc_missings))
intersection_point <- intersection$root
intersection_point

```


```{r compare-all-IDK-FFT-handle}

# define the costs of false decision where all_IDK and FFT_handle fucntion meet:
costs_false_decisions <- c(costs_false_intersections_05[4],
costs_false_intersections_10[4],
costs_false_intersections_20[4],
costs_false_intersections_25[4], 
costs_false_intersections_50[4],
costs_false_intersections_60[4],
costs_false_intersections_75[4],
costs_false_intersections_100[4])

# define pc that is missing: 
pc_missings <- c(5, 10, 20, 25, 50, 60, 75, 100)

# plot both and a vertical line at 0, that is the cost of IDK decisions: 
plot(pc_missings, costs_false_decisions , type='o',lty=2,ylim = c(-4,2),col='darkgreen',lwd=1,  main = "Costs of False decisions, where when more expensive all_IDK starts performing better than FFT_handle.")
abline(h = 0, col='red',lty = 2)

```






```{r compare-1-IDK-FFT-handle}



threshold <- c(-99.71304,-32.38616,-7.6627054 ,-1.363036, -0.3513262, 0.08250825)
pc_missings <- c(5, 10, 25, 50, 75, 100)

plot(pc_missings, threshold , type='o',lty=2,col='darkgreen',lwd=1, main = "Costs of IDK decisions, where when lower 1_IDK starts performing better than FFT_handle.")


```


```{r compare-all-IDK-FFT-handle}

threshold <- c(0.5292303, 0.5600749,0.3933815,0.3342763, 0.2020955, 0.08250825)
pc_missings <- c(5, 10, 25, 50, 75, 100)

plot(pc_missings, threshold, type='o',lty=2,col='darkgreen',lwd=1, main = "Costs of IDK decisions, where when lower all_IDK starts performing better than FFT_handle.")


```

